package com.demo.kmp.android.dao

class UserDao {
    fun getAllUser() = arrayOf(
        User(
            login = "jvantuyl",
            id = 101,
            nodeId = "MDQ6VXNlcjEwMQ==",
            avatarUrl = "https://avatars.githubusercontent.com/u/101?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/jvantuyl",
            htmlUrl = "https://github.com/jvantuyl",
            followersUrl = "https://api.github.com/users/jvantuyl/followers",
            followingUrl = "https://api.github.com/users/jvantuyl/following{/other_user}",
            gistsUrl = "https://api.github.com/users/jvantuyl/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/jvantuyl/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/jvantuyl/subscriptions",
            organizationsUrl = "https://api.github.com/users/jvantuyl/orgs",
            reposUrl = "https://api.github.com/users/jvantuyl/repos",
            eventsUrl = "https://api.github.com/users/jvantuyl/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/jvantuyl/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        ),
        User(
            login = "BrianTheCoder",
            id = 102,
            nodeId = "MDQ6VXNlcjEwMg==",
            avatarUrl = "https://avatars.githubusercontent.com/u/102?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/BrianTheCoder",
            htmlUrl = "https://github.com/BrianTheCoder",
            followersUrl = "https://api.github.com/users/BrianTheCoder/followers",
            followingUrl = "https://api.github.com/users/BrianTheCoder/following{/other_user}",
            gistsUrl = "https://api.github.com/users/BrianTheCoder/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/BrianTheCoder/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/BrianTheCoder/subscriptions",
            organizationsUrl = "https://api.github.com/users/BrianTheCoder/orgs",
            reposUrl = "https://api.github.com/users/BrianTheCoder/repos",
            eventsUrl = "https://api.github.com/users/BrianTheCoder/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/BrianTheCoder/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        ),
        User(
            login = "freeformz",
            id = 103,
            nodeId = "MDQ6VXNlcjEwMw==",
            avatarUrl = "https://avatars.githubusercontent.com/u/103?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/freeformz",
            htmlUrl = "https://github.com/freeformz",
            followersUrl = "https://api.github.com/users/freeformz/followers",
            followingUrl = "https://api.github.com/users/freeformz/following{/other_user}",
            gistsUrl = "https://api.github.com/users/freeformz/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/freeformz/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/freeformz/subscriptions",
            organizationsUrl = "https://api.github.com/users/freeformz/orgs",
            reposUrl = "https://api.github.com/users/freeformz/repos",
            eventsUrl = "https://api.github.com/users/freeformz/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/freeformz/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        ),
        User(
            login = "hassox",
            id = 104,
            nodeId = "MDQ6VXNlcjEwNA==",
            avatarUrl = "https://avatars.githubusercontent.com/u/104?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/hassox",
            htmlUrl = "https://github.com/hassox",
            followersUrl = "https://api.github.com/users/hassox/followers",
            followingUrl = "https://api.github.com/users/hassox/following{/other_user}",
            gistsUrl = "https://api.github.com/users/hassox/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/hassox/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/hassox/subscriptions",
            organizationsUrl = "https://api.github.com/users/hassox/orgs",
            reposUrl = "https://api.github.com/users/hassox/repos",
            eventsUrl = "https://api.github.com/users/hassox/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/hassox/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        ),
        User(
            login = "automatthew",
            id = 105,
            nodeId = "MDQ6VXNlcjEwNQ==",
            avatarUrl = "https://avatars.githubusercontent.com/u/105?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/automatthew",
            htmlUrl = "https://github.com/automatthew",
            followersUrl = "https://api.github.com/users/automatthew/followers",
            followingUrl = "https://api.github.com/users/automatthew/following{/other_user}",
            gistsUrl = "https://api.github.com/users/automatthew/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/automatthew/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/automatthew/subscriptions",
            organizationsUrl = "https://api.github.com/users/automatthew/orgs",
            reposUrl = "https://api.github.com/users/automatthew/repos",
            eventsUrl = "https://api.github.com/users/automatthew/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/automatthew/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        ),
        User(
            login = "queso",
            id = 106,
            nodeId = "MDQ6VXNlcjEwNg==",
            avatarUrl = "https://avatars.githubusercontent.com/u/106?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/queso",
            htmlUrl = "https://github.com/queso",
            followersUrl = "https://api.github.com/users/queso/followers",
            followingUrl = "https://api.github.com/users/queso/following{/other_user}",
            gistsUrl = "https://api.github.com/users/queso/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/queso/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/queso/subscriptions",
            organizationsUrl = "https://api.github.com/users/queso/orgs",
            reposUrl = "https://api.github.com/users/queso/repos",
            eventsUrl = "https://api.github.com/users/queso/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/queso/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        ),
        User(
            login = "lancecarlson",
            id = 107,
            nodeId = "MDQ6VXNlcjEwNw==",
            avatarUrl = "https://avatars.githubusercontent.com/u/107?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/lancecarlson",
            htmlUrl = "https://github.com/lancecarlson",
            followersUrl = "https://api.github.com/users/lancecarlson/followers",
            followingUrl = "https://api.github.com/users/lancecarlson/following{/other_user}",
            gistsUrl = "https://api.github.com/users/lancecarlson/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/lancecarlson/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/lancecarlson/subscriptions",
            organizationsUrl = "https://api.github.com/users/lancecarlson/orgs",
            reposUrl = "https://api.github.com/users/lancecarlson/repos",
            eventsUrl = "https://api.github.com/users/lancecarlson/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/lancecarlson/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        ),
        User(
            login = "drnic",
            id = 108,
            nodeId = "MDQ6VXNlcjEwOA==",
            avatarUrl = "https://avatars.githubusercontent.com/u/108?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/drnic",
            htmlUrl = "https://github.com/drnic",
            followersUrl = "https://api.github.com/users/drnic/followers",
            followingUrl = "https://api.github.com/users/drnic/following{/other_user}",
            gistsUrl = "https://api.github.com/users/drnic/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/drnic/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/drnic/subscriptions",
            organizationsUrl = "https://api.github.com/users/drnic/orgs",
            reposUrl = "https://api.github.com/users/drnic/repos",
            eventsUrl = "https://api.github.com/users/drnic/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/drnic/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        ),
        User(
            login = "lukesutton",
            id = 109,
            nodeId = "MDQ6VXNlcjEwOQ==",
            avatarUrl = "https://avatars.githubusercontent.com/u/109?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/lukesutton",
            htmlUrl = "https://github.com/lukesutton",
            followersUrl = "https://api.github.com/users/lukesutton/followers",
            followingUrl = "https://api.github.com/users/lukesutton/following{/other_user}",
            gistsUrl = "https://api.github.com/users/lukesutton/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/lukesutton/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/lukesutton/subscriptions",
            organizationsUrl = "https://api.github.com/users/lukesutton/orgs",
            reposUrl = "https://api.github.com/users/lukesutton/repos",
            eventsUrl = "https://api.github.com/users/lukesutton/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/lukesutton/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        ),
        User(
            login = "danwrong",
            id = 110,
            nodeId = "MDQ6VXNlcjExMA==",
            avatarUrl = "https://avatars.githubusercontent.com/u/110?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/danwrong",
            htmlUrl = "https://github.com/danwrong",
            followersUrl = "https://api.github.com/users/danwrong/followers",
            followingUrl = "https://api.github.com/users/danwrong/following{/other_user}",
            gistsUrl = "https://api.github.com/users/danwrong/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/danwrong/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/danwrong/subscriptions",
            organizationsUrl = "https://api.github.com/users/danwrong/orgs",
            reposUrl = "https://api.github.com/users/danwrong/repos",
            eventsUrl = "https://api.github.com/users/danwrong/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/danwrong/received_events",
            type = "User",
            userViewType = "public",
            siteAdmin = false
        )
    )
}